<div style="color:white;
           display:fill;
           border-radius:5px;
           background-color:#5642C5;
           font-size:200%;
           font-\amily:Arial;letter-spacing:0.5px">

<p width = 20%, style="padding: 10px;
              color:white;">
Object Oriented Programming
              
</p>
</div>

Data Science Cohort Live NYC Nov 2023
<p>Phase 3: Topic 21</p>
<br>
<br>

<div align = "right">
<img src="Images/flatiron-school-logo.png" align = "right" width="200"/>
</div>

#### Objected Oriented Programming

- We've actually been using this without realizing it.


#### Examples

- results object in statsmodels OLS fit
- requests object or BeautifulSoup objects in web scraping
- sklearn LinearRegression models
- fig and ax objects in Matplotlib

#### Object Oriented Program in a Nutshell

<center><img src = "Images/pikachu.png" width = 800 /></center>

- Class: Pokemon
- object instance of Pokemon class

- Attributes = Fields. Properties of object instance.
- Methods: an action. Can change state of object instance.

<center><img src = "Images/pikachu.png" width = 800 /></center>

-  **Class**: general class of similar objects
- Want common attributes/methods for each instantiated object

**Pokemon is general class. Pikachu is an object of class Pokemon.**

<center><img src = "Images/pikachu.png" width = 800 /></center>

**Fields/Attributes**:
- objects of same class share same attributes
- each attribute takes on different values for different instantiations.
    
e.g., Name, Type, Health attributes common to all pokemons


But Pikachu and Bulbasaur:
- different values of attributes.

<center><img src = "Images/pikachu.png" width = 800 /></center>

**Methods**:
- Objects in given Class can execute common set of functions
- Functions can change internal state of object
    - i.e. change attributes: .evolve() can change health, name, etc.

#### Creating a class in Python

Create simple class using class constructor and initialization:

In [1]:
class Pokemon:

    def __init__(self, name, lvl, health, attack_points, defense_points):
        
        self.name = name
        self.level = lvl
        self.life = health
        self.attack_power = attack_points
        self.defense_points = defense_points
        

the __init__ method is a special function:

- the first argument is always: *self*
- *self* refers to specific instance of class. 
- the other arguments: initalization arguments 
    - user specified inputs in initializing instance.
    - can have default arguments


In [2]:
class Pokemon:
    
    def __init__(self, name, lvl, health, attack_points, defense_points):
        
        self.name = name
        self.level = lvl
        self.life = health
        self.attack_power = attack_points
        self.defense_points = defense_points
        

#### Let's see this in action 

Create an instance of a Pokemon:
- Create and instantiate a Pikachu.

In [3]:
pikachu = Pokemon('Pikachu', 2, 70, 7, 4)

Let's check out some of the attributes

In [7]:
pikachu.life

70

In [6]:
class Pokemon:
    
    def __init__(self, name, lvl, health, attack_points, defense_points):
        
        self.name = name
        self.level = lvl
        self.life = health
        self.attack_power = attack_points
        self.defense_points = defense_points

- So far the class object is like a grouping of variables (like a dict). 
- Adding methods give class objects a richer structure

#### Methods

- Create functions that:
    - return object state
    - update object state (i.e. change internal attributes)
    - do it based on information external to object.


In [8]:
class Pokemon:
    
    def __init__(self, name, lvl, health, attack_points, defense_points):
        
        self.name = name
        self.level = lvl
        self.life = health
        self.attack_power = attack_points
        self.defense_points = defense_points
    
    def get_state(self):
        
        state_dict = {'name': self.name, 'level': self.level, 'life': self.life,
                     'attack': self.attack_power, 'defense': self.defense_points}
        return state_dict
        
    def evolve(self, evolved_name):
        #Change Pokemon name to given evolved name state
        self.name = evolved_name
        
        #level up the stats
        self.level += 1
        self.life += 30
        self.attack_power += 4
        self.defense_points += 3

In [9]:
pikachu = Pokemon('Pikachu', 2, 70, 7, 4)

In [10]:
pikachu.get_state()

{'name': 'Pikachu', 'level': 2, 'life': 70, 'attack': 7, 'defense': 4}

<img src = "Images/evolution_phases.jpeg" width = 700 />

In [11]:
pikachu.evolve('Raichu')

In [12]:
pikachu.get_state()

{'name': 'Raichu', 'level': 3, 'life': 100, 'attack': 11, 'defense': 7}

Let's have fun with another class:
- Create a koala class with each instance a koala that eats bunches of eucalyptus and poops.
- Each bunch of eucalyptus weighs a pound.
- Pooping gets rid of half a pound.
- If the load in the koala's belly goes past 6 pounds:
    - the koala dies by belly explosion.

<center><img src = "Images/gastro.jpg" width = 1000/></center>

Your data science instructor really doesn't get this objected oriented programming stuff! Help him out.

In [13]:
class Koala:
    
    # first need to initialize. 
    #define relevant variables.
    def __init__(self, belly_weight, name, alive = 'Alive'):
        self.weight = belly_weight
        self.name = name
        self.status = alive
        
    def alive_status(self):
        if self.weight > 6:
            self.status = 'Dead'
        else:
            pass
        return self.status
            
    def eat_eucalyptus(self, num_bunches = 1):
        if self.status == 'Alive':
            self.weight += num_bunches
        else:
            print("Dead koalas dont eat")
        
    # create poop() method
    def poop(self, poop_weight = 0.5):
        if self.status == 'Alive':
            self.weight -= poop_weight
        else:
            print("Dead koalas don't poop.")
    

In [16]:
koala1 = Koala(2, 'Randy')
koala1

In [17]:
koala1.weight

2

In [18]:
koala1.alive_status()

'Alive'

In [19]:
koala1.eat_eucalyptus()

In [20]:
koala1.weight

3

In [21]:
koala1.poop()

In [22]:
koala1.weight

2.5

In [23]:
koala1.alive_status()

'Alive'

In [24]:
koala1.eat_eucalyptus(8)

In [25]:
koala1.alive_status()

'Dead'

In [26]:
koala1.poop()

Dead koalas don't poop.



- Each bunch of eucalyptus weighs a pound.
- Pooping gets rid of half a pound.
- If the load in the koala's belly goes past 6 pounds:
    - the koala dies by belly explosion.

Now for why all this is relevant to our work in data science.

In [27]:
class Standardizer:
    
    def __init__(self):
        self.mean_series = None
        self.stdev_series = None
    
    def fit(self, data):
        self.mean_series = data.mean()
        self.stdev_series = data.std(ddof = 1)
        
    def transform(self, X):
        X_standard = (X - self.mean_series)/self.stdev_series 
        return X_standard
    
    def fit_transform(self, X):
        #fit with X
        self.fit(X)
        #apply transformation to X
        transformed = self.transform(X)
        return transformed      

In [28]:
import pandas as pd
heart_df = pd.read_csv('Data/heart.csv', usecols = ['age', 'chol', 'thalach', 'target'])
heart_df.head()

age  chol  thalach  target
0   63   233      150       1
1   37   250      187       1
2   41   204      172       1
3   56   236      178       1
4   57   354      163       1

Split into train and test sets.

In [29]:
from sklearn.model_selection import train_test_split
X = heart_df.drop(columns = ['target'])
y = heart_df['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

Let's use our standardizer class! 
- Instantiate transformer object.
- Fit our standardizer object to the training set.

In [30]:
sd = Standardizer()

In [31]:
sd.mean_series

In [32]:
sd.stdev_series

Fit the transformer.

In [33]:
sd.fit(X_train)

In [34]:
sd.mean_series

age         54.243802
chol       245.214876
thalach    149.888430
dtype: float64

In [35]:
sd.stdev_series

age         8.941631
chol       49.130060
thalach    22.513250
dtype: float64

Means and standard deviations for each column:
- extracted (fit) from training set.
- use these parameters to transform both train and test

#### Transform train set

In [36]:
X_train_standard = sd.transform(X_train)
X_train_standard.head()

age      chol   thalach
282  0.531916 -0.553935 -0.705737
202  0.420080  0.504480 -1.727357
83  -0.250939  1.074396  1.248668
171 -0.698284 -0.330040  0.804485
178 -1.257467 -1.388455 -1.327593

In [37]:
X_train_standard.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 242 entries, 282 to 273
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   age      242 non-null    float64
 1   chol     242 non-null    float64
 2   thalach  242 non-null    float64
dtypes: float64(3)
memory usage: 7.6 KB


In [39]:
X_train_standard.mean()


age       -3.424717e-16
chol      -2.540438e-16
thalach   -5.826377e-17
dtype: float64

#### Transform test set
- Use fitted parameters to transform test set.

In [40]:
X_test_standard = sd.transform(X_test)
X_test_standard.head()

age      chol   thalach
261 -0.250939 -0.309686  0.449139
294 -1.145630 -1.551288 -0.261554
231  0.308243  0.891208 -1.149920
7   -1.145630  0.362001  1.026576
276  0.420080 -0.553935 -1.993867

In [42]:
X_test_standard.mean()

age        0.068070
chol       0.106073
thalach   -0.053298
dtype: float64

Scikit-learn transformers are instances of class objects.

In [43]:
from sklearn.preprocessing import StandardScaler
sklearn_sd = StandardScaler()

X_train_sklearn = sklearn_sd.fit_transform(X_train)

In [44]:
sklearn_sd.mean_

array([ 54.24380165, 245.21487603, 149.88842975])

In [45]:
sklearn_sd.scale_

array([ 8.92313728, 49.02844622, 22.46668678])

Looking at the desciptive statistics of the transformed $X_{train}$:

In [46]:
print(X_train_sklearn.mean(axis = 0))

[-2.71591748e-16 -2.12869208e-16 -3.30314288e-17]


In [47]:
print(X_train_sklearn.std(axis = 0))

[1. 1. 1.]


Yeah, its doing the same thing as our hard-coded class.

#### Models in scikit-learn
- Also classes with different methods.
- .fit()
- .predict()
- .fit_predict()
- .score(X,y)

LinearRegression() was an example.

In [48]:
from numpy import linalg # linear algebra subpackage
import numpy as np

Implementing custom OLS linear regression class:
- sklearn model doing similar things under hood of
    - .fit(X,y) method
    - .predict(X) method
    - etc.

In [49]:
class CustomLinearRegression:
    
    def __init__(self):
        self.intercept = None
        self.coeff = None
        
    def fit(self, X_in, y):
        
        #create a column of 1s for offset fitting
        bias_col = np.ones(X_in.shape[0]).reshape(-1,1) 
    
        #augmented data matrix with column of ones
        X = np.hstack((bias_col, X_in))
        
        # weights: result of least squares minimization
        w = linalg.inv(X.T@X)@(X.T@y)
        # its a formula
        
        self.intercept = w[0]
        self.coeff = w[1::]
        
    # same as y = beta_0 + beta_1*x_1 + beta_2*x_2 + ... + beta_n*x_n
    #just more compact. we'll see later.
    def predict(self, X):
        y_pred = X@self.coeff + self.intercept
        return y_pred
    

Create instances of our custom model and scikit-learn linear regression model

In [50]:
from sklearn.linear_model import LinearRegression
clr = CustomLinearRegression()
sklearn_lr = LinearRegression()

Scikit-learn linear regression .fit() method:
- find weights/model parameters

In [51]:
clr.fit(X_train, y_train)
sklearn_lr.fit(X_train, y_train)

LinearRegression()

In [52]:
clr.intercept

-0.34681990883454716

In [53]:
sklearn_lr.intercept_

-0.34681990883452807


Under the hood, sklearn model is:

Class object with model parameters as attributes.

- .fit(X,y) method uses formula or algorithm to find model parameters (weights)
- used X, y as training data

- .predict(X) 
    - learned parameters + X into model
    - get prediction

In [54]:
clr.predict(X_test)[0:5]

261    0.660241
294    0.588182
231    0.308414
7      0.796194
276    0.170947
dtype: float64

In [55]:
sklearn_lr.predict(X_test)[0:5]

array([0.66024086, 0.58818226, 0.30841357, 0.79619367, 0.17094749])

We showed:
- Clearly how sklearn works under the hood via class objects   
- But not integrated into the scikit-learn library
    


Next: 
- Learn about parent/child classes
- Inheritance and class hierarchy
- Integrate our models/transformers into scikit-learn class hierarchy.